version: "3.3"

services:
  postgres:
    image: postgres:12.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

